//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreetSmartArcMap.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StreetSmartArcMap.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CycloMedia Technology B.V. (‘CycloMedia’) is registered in the Trade Register
        ///of the Chamber of Commerce under number 16063843.
        ///
        ///USER TERMS AND CONDITIONS STREET SMART
        ///The usage of Image Material and/or the Information Products and the Software 
        ///as a Service Services (‘SaaS Services’) made available via Street Smart by 
        ///means of an agreement with the organization for which you work, be it as an
        ///employee or on assignment basis, is only permitted under the following terms
        ///and conditions.
        ///
        ///Definition [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Agreement {
            get {
                return ResourceManager.GetString("Agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save anyway?.
        /// </summary>
        internal static string ConfigurationAsk {
            get {
                return ResourceManager.GetString("ConfigurationAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not have a value..
        /// </summary>
        internal static string InvalidApiPassword {
            get {
                return ResourceManager.GetString("InvalidApiPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclorama viewer does not have a value..
        /// </summary>
        internal static string InvalidApiSRS {
            get {
                return ResourceManager.GetString("InvalidApiSRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username does not have a value..
        /// </summary>
        internal static string InvalidApiUsername {
            get {
                return ResourceManager.GetString("InvalidApiUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed.
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Successfully.
        /// </summary>
        internal static string LoginSuccessfully {
            get {
                return ResourceManager.GetString("LoginSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Smart for ArcMap.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
